theme: jekyll-theme-cayman
title: Towamba Rural
# description: [A short description of your site's purpose]
google_analytics: UA-148458275-1

# plugins:
#   - jekyll-remote-theme
# remote_theme: benbalter/retlab
