backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown